--- 
abstract: Use WebService::Lucene in your Catalyst application
author: 
  - Brian Cassidy <bricas@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-WebService-Lucene
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.7000
  WebService::Lucene: 0
version: 0.04
